# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import proyecto3.fotos_mascotas.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('foto_ubicacion', models.FileField(null=True, upload_to=proyecto3.fotos_mascotas.models.directorio_fotos)),
                ('fecha_subida', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
